DC_characters = ["Bat man", "Super Man", "Aqua man", "Flash",
                 "Wonder Woman", "Super Girl", "Bat girl", "Beasy boy",
                 "Big Brada", "Captain Atom", "Black Canary", "Captain Cold",
                 "Harley Quinn", "Captain Boomrang", "DeadShot", "King Shark",
                 "Cyborg", "Green Lantern", "Atom Smasher", "Black Manta",
                 "Bumble Bee", "Donna Troy", "Doomsday", "Eve Coffin"]

marvel_characters = ["Captain America", "Iron Man", "Blck Widow", "The Hulk",
                     "Black Panther", "Spider man", "Thor", "Ant-Man",
                     "Captain Marvel", "Hawk Eye", "Loki", "Daredevil",
                     "Punisher", "Deadpool", "Nick Fury", "Bucky Barns",
                     "Dr. Strange", "War Machine", "Moon Knight", "Carol Danvers",
                     "Vision", "Wasp", "Scarlet Witch", "Jessica Jones",
                     "Shang-Chi", "Agent Mobius", "Ayo", "Goose",
                     "The Collector", "Corvus Glaive", "Black Knight",
                     "Durig", "Sersi", "Kro", "Thena", "Darr-Ben",
                     "Groot", "Star-Lord", "Drax", "Yonda",
                     "Gamora", "Nebula", "Rocket", "Cosmo",
                     "Thanos", "Ronan", "Shuri", "Hank Pym",
                     "Okoye", "Ultron", "QuickSilver", "Phil Coulson",
                     "Nakia", "Killmonger", "Zuri", "M'Baku",
                     "Abomination", "Absorbing Man", "Xavier",
                     "Valkin", "valkyrie", "Vapor", "vector",
                     "Wave", "Woody", "Uatu", "Ulik",
                     "THunderbolt", "Triton", "Sabre tooth", "Sandman",
                     "Scorpion", "Shocker", "Storm", "Red Skull",
                     "Rogue", "Quake", "Pyro", "Odin",
                     "Hela", "Frigga", "Heimdall", "Sif",
                     "Wong", "Ancient One", "Howard Stark", "Falcon",
                     "Ka-Zar", "Iron-Fist", "Elektra", "Electro",
                     "Daisy Johnson", "Deke Shaw", "Assassin Spider man",
                     "Kingpin", "The Spot", "Miles Morales", "Scarlet Spider",
                     "The Prowler", "Blade"]
