use dist_bf;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(128) NOT NULL UNIQUE,
    created_by VARCHAR(64) NOT NULL
);

CREATE TABLE pending_users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL UNIQUE,
    update_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    updated_by VARCHAR(64) NOT NULL
);

CREATE TABLE sync_filter (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bloom_filter LONGBLOB NOT NULL,
    entries INTEGER NOT NULL,
    updated_by VARCHAR(256) 
);
