INSERT INTO USERS ( username, created_by) values ("Captain America", "main_server");
INSERT INTO USERS ( username, created_by) values ("Iron Man", "main_server");
INSERT INTO USERS ( username, created_by) values ("Blck Widow", "main_server");
INSERT INTO USERS ( username, created_by) values ("The Hulk", "main_server");
INSERT INTO USERS ( username, created_by) values ("Black Panther", "main_server");
INSERT INTO USERS ( username, created_by) values ("Spider man", "main_server");
INSERT INTO USERS ( username, created_by) values ("Thor", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ant-Man", "main_server");
INSERT INTO USERS ( username, created_by) values ("Captain Marvel", "main_server");
INSERT INTO USERS ( username, created_by) values ("Hawk Eye", "main_server");
INSERT INTO USERS ( username, created_by) values ("Loki", "main_server");
INSERT INTO USERS ( username, created_by) values ("Daredevil", "main_server");
INSERT INTO USERS ( username, created_by) values ("Punisher", "main_server");
INSERT INTO USERS ( username, created_by) values ("Deadpool", "main_server");
INSERT INTO USERS ( username, created_by) values ("Nick Fury", "main_server");
INSERT INTO USERS ( username, created_by) values ("Bucky Barns", "main_server");
INSERT INTO USERS ( username, created_by) values ("Dr. Strange", "main_server");
INSERT INTO USERS ( username, created_by) values ("War Machine", "main_server");
INSERT INTO USERS ( username, created_by) values ("Moon Knight", "main_server");
INSERT INTO USERS ( username, created_by) values ("Carol Danvers", "main_server");
INSERT INTO USERS ( username, created_by) values ("Vision", "main_server");
INSERT INTO USERS ( username, created_by) values ("Wasp", "main_server");
INSERT INTO USERS ( username, created_by) values ("Scarlet Witch", "main_server");
INSERT INTO USERS ( username, created_by) values ("Jessica Jones", "main_server");
INSERT INTO USERS ( username, created_by) values ("Shang-Chi", "main_server");
INSERT INTO USERS ( username, created_by) values ("Agent Mobius", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ayo", "main_server");
INSERT INTO USERS ( username, created_by) values ("Goose", "main_server");
INSERT INTO USERS ( username, created_by) values ("The Collector", "main_server");
INSERT INTO USERS ( username, created_by) values ("Corvus Glaive", "main_server");
INSERT INTO USERS ( username, created_by) values ("Black Knight", "main_server");
INSERT INTO USERS ( username, created_by) values ("Durig", "main_server");
INSERT INTO USERS ( username, created_by) values ("Sersi", "main_server");
INSERT INTO USERS ( username, created_by) values ("Kro", "main_server");
INSERT INTO USERS ( username, created_by) values ("Thena", "main_server");
INSERT INTO USERS ( username, created_by) values ("Darr-Ben", "main_server");
INSERT INTO USERS ( username, created_by) values ("Groot", "main_server");
INSERT INTO USERS ( username, created_by) values ("Star-Lord", "main_server");
INSERT INTO USERS ( username, created_by) values ("Drax", "main_server");
INSERT INTO USERS ( username, created_by) values ("Yonda", "main_server");
INSERT INTO USERS ( username, created_by) values ("Gamora", "main_server");
INSERT INTO USERS ( username, created_by) values ("Nebula", "main_server");
INSERT INTO USERS ( username, created_by) values ("Rocket", "main_server");
INSERT INTO USERS ( username, created_by) values ("Cosmo", "main_server");
INSERT INTO USERS ( username, created_by) values ("Thanos", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ronan", "main_server");
INSERT INTO USERS ( username, created_by) values ("Shuri", "main_server");
INSERT INTO USERS ( username, created_by) values ("Hank Pym", "main_server");
INSERT INTO USERS ( username, created_by) values ("Okoye", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ultron", "main_server");
INSERT INTO USERS ( username, created_by) values ("QuickSilver", "main_server");
INSERT INTO USERS ( username, created_by) values ("Phil Coulson", "main_server");
INSERT INTO USERS ( username, created_by) values ("Nakia", "main_server");
INSERT INTO USERS ( username, created_by) values ("Killmonger", "main_server");
INSERT INTO USERS ( username, created_by) values ("Zuri", "main_server");
INSERT INTO USERS ( username, created_by) values ("M'Baku", "main_server");
INSERT INTO USERS ( username, created_by) values ("Abomination", "main_server");
INSERT INTO USERS ( username, created_by) values ("Absorbing Man", "main_server");
INSERT INTO USERS ( username, created_by) values ("Xavier", "main_server");
INSERT INTO USERS ( username, created_by) values ("Valkin", "main_server");
INSERT INTO USERS ( username, created_by) values ("valkyrie", "main_server");
INSERT INTO USERS ( username, created_by) values ("Vapor", "main_server");
INSERT INTO USERS ( username, created_by) values ("vector", "main_server");
INSERT INTO USERS ( username, created_by) values ("Wave", "main_server");
INSERT INTO USERS ( username, created_by) values ("Woody", "main_server");
INSERT INTO USERS ( username, created_by) values ("Uatu", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ulik", "main_server");
INSERT INTO USERS ( username, created_by) values ("THunderbolt", "main_server");
INSERT INTO USERS ( username, created_by) values ("Triton", "main_server");
INSERT INTO USERS ( username, created_by) values ("Sabre tooth", "main_server");
INSERT INTO USERS ( username, created_by) values ("Sandman", "main_server");
INSERT INTO USERS ( username, created_by) values ("Scorpion", "main_server");
INSERT INTO USERS ( username, created_by) values ("Shocker", "main_server");
INSERT INTO USERS ( username, created_by) values ("Storm", "main_server");
INSERT INTO USERS ( username, created_by) values ("Red Skull", "main_server");
INSERT INTO USERS ( username, created_by) values ("Rogue", "main_server");
INSERT INTO USERS ( username, created_by) values ("Quake", "main_server");
INSERT INTO USERS ( username, created_by) values ("Pyro", "main_server");
INSERT INTO USERS ( username, created_by) values ("Odin", "main_server");
INSERT INTO USERS ( username, created_by) values ("Hela", "main_server");
INSERT INTO USERS ( username, created_by) values ("Frigga", "main_server");
INSERT INTO USERS ( username, created_by) values ("Heimdall", "main_server");
INSERT INTO USERS ( username, created_by) values ("Sif", "main_server");
INSERT INTO USERS ( username, created_by) values ("Wong", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ancient One", "main_server");
INSERT INTO USERS ( username, created_by) values ("Howard Stark", "main_server");
INSERT INTO USERS ( username, created_by) values ("Falcon", "main_server");
INSERT INTO USERS ( username, created_by) values ("Ka-Zar", "main_server");
INSERT INTO USERS ( username, created_by) values ("Iron-Fist", "main_server");
INSERT INTO USERS ( username, created_by) values ("Elektra", "main_server");
INSERT INTO USERS ( username, created_by) values ("Electro", "main_server");
INSERT INTO USERS ( username, created_by) values ("Daisy Johnson", "main_server");
INSERT INTO USERS ( username, created_by) values ("Deke Shaw", "main_server");
INSERT INTO USERS ( username, created_by) values ("Assassin Spider man", "main_server");
INSERT INTO USERS ( username, created_by) values ("Kingpin", "main_server");
INSERT INTO USERS ( username, created_by) values ("The Spot", "main_server");
INSERT INTO USERS ( username, created_by) values ("Miles Morales", "main_server");
INSERT INTO USERS ( username, created_by) values ("Scarlet Spider", "main_server");
INSERT INTO USERS ( username, created_by) values ("The Prowler", "main_server");
INSERT INTO USERS ( username, created_by) values ("Blade", "main_server");

INSERT INTO sync_filter (bloom_filter, entries, updated_by) values('00111110110111011110011011110111111111011011101110101101010110111011011011111111111111111001111101111110111111111111110010111111101111011111100101110110111110011111111111110011011110111111111011011001111101011111110011100111100101101000010111111011111111111111110110111111110101111011110010111111101111111111111011111011111011010110111111100011110010110111100111111111100111101101110110011111111101010011111111111111011110101110111111010101110011101011111111101111111111111111110',
100, "main_server");
