DC_characters = ["Bat man", "Super Man", "Aqua man", "Flash",
                 "Wonder Woman", "Super Girl", "Bat girl", "Beasy boy",
                 "Big Brada", "Captain Atom", "Black Canary", "Captain Cold",
                 "Harley Quinn", "Captain Boomrang", "DeadShot", "King Shark",
                 "Cyborg", "Green Lantern", "Atom Smasher", "Black Manta",
                 "Bumble Bee", "Donna Troy", "Doomsday", "Eve Coffin"]

marvel_characters = ["Captain America", "Iron Man", "Blck Widow", "The Hulk",
                     "Black Panther", "Spider man", "Thor", "Ant-Man",
                     "Captain Marvel", "Hawk Eye", "Loki", "Daredevil",
                     "Punisher", "Deadpool", "Nick Fury", "Bucky Barns",
                     "Dr. Strange", "War Machine", "Moon Knight", "Carol Danvers",
                     "Vision", "Wasp", "Scarlet Witch", "Jessica Jones",
                     "Shang-Chi", "Agent Mobius", "Ayo", "Goose",
                     "The Collector", "Corvus Glaive", "Black Knight",
                     "Durig", "Sersi", "Kro", "Thena", "Darr-Ben",
                     "Groot", "Star-Lord", "Drax", "Yonda",
                     "Gamora", "Nebula", "Rocket", "Cosmo",
                     "Thanos", "Ronan", "Shuri", "Hank Pym",
                     "Okoye", "Ultron", "QuickSilver", "Phil Coulson",
                     "Nakia", "Killmonger", "Zuri", "M'Baku",
                     "Abomination", "Absorbing Man", "Xavier",
                     "Valkin", "valkyrie", "Vapor", "vector",
                     "Wave", "Woody", "Uatu", "Ulik",
                     "THunderbolt", "Triton", "Sabre tooth", "Sandman",
                     "Scorpion", "Shocker", "Storm", "Red Skull",
                     "Rogue", "Quake", "Pyro", "Odin",
                     "Hela", "Frigga", "Heimdall", "Sif",
                     "Wong", "Ancient One", "Howard Stark", "Falcon",
                     "Ka-Zar", "Iron-Fist", "Elektra", "Electro",
                     "Daisy Johnson", "Deke Shaw", "Assassin Spider man",
                     "Kingpin", "The Spot", "Miles Morales", "Scarlet Spider",
                     "The Prowler", "Blade"]

DC_characters1 = ["Superman", "Batman", "Wonder Woman", "Flash (Barry Allen)", "Aquaman", "Green Lantern (Hal Jordan)",
                  "Martian Manhunter", "Green Arrow", "Black Canary", "Cyborg", "Nightwing", "Robin (Damian Wayne)",
                  "Supergirl", "Batgirl (Barbara Gordon)", "Hawkman", "Hawkgirl", "Shazam (Billy Batson)", "Zatanna",
                  "Constantine", "Firestorm", "Blue Beetle (Jaime Reyes)", "Booster Gold", "Doctor Fate", "Vixen",
                  "The Atom (Ray Palmer)", "Captain Atom", "Red Tornado", "Mister Miracle", "Big Barda", "Animal Man",
                  "Plastic Man", "Swamp Thing", "Stargirl", "Wildcat", "Huntress", "Black Lightning", "Raven",
                  "Starfire", "Beast Boy", "Kid Flash (Wally West)", "Red Hood (Jason Todd)", "Batwoman (Kate Kane)",
                  "Catwoman", "Harley Quinn", "Poison Ivy", "The Joker", "Lex Luthor", "Darkseid", "Brainiac",
                  "Sinestro", "Deathstroke", "Ra's al Ghul", "Talia al Ghul", "Black Adam", "Bane", "Cheetah",
                  "Reverse-Flash (Eobard Thawne)", "Captain Cold", "Gorilla Grodd", "Doomsday", "General Zod",
                  "Riddler", "Penguin", "Two-Face", "Scarecrow", "Killer Croc", "Clayface", "Solomon Grundy",
                  "Deadshot", "Amanda Waller", "Enchantress", "Parasite", "Metallo", "Ares", "Doctor Sivana",
                  "Black Manta", "Ocean Master", "Hush", "The Court of Owls (Talon)", "Mister Freeze", "Lady Shiva",
                  "Prometheus", "Maxwell Lord", "Anti-Monitor", "Superboy (Kon-El)", "Power Girl",
                  "The Spectre (Jim Corrigan)", "Etrigan the Demon", "Phantom Stranger", "Lobo", "Jonah Hex", "Orion",
                  "The Question (Vic Sage)", "Azrael", "The Creeper", "Hawk (Hank Hall)", "Dove (Dawn Granger)",
                  "Elongated Man", "Katana", "The Phantom", "Maxwell Lord", "Granny Goodness", "Atrocitus", "Larfleeze",
                  "Saint Walker", "Mera", "Red Lantern (Bleez)", "Doctor Light", "Vandal Savage", "Doctor Polaris",
                  "Mister Mxyzptlk", "The Shade", "Felix Faust", "Klarion the Witch Boy", "Starro", "Queen Bee",
                  "Brother Blood", "The Floronic Man", "Mongul", "Captain Boomerang", "Livewire", "Killer Frost",
                  "Silver Banshee", "Cheshire", "Roulette", "Firefly", "Hugo Strange", "Calendar Man", "Man-Bat",
                  "KGBeast", "Punchline", "Mad Hatter", "Lady Blackhawk", "The Monitor", "Nekron", "Black Hand",
                  "Black Mask", "Deadman", "Ragman", "Ozymandias", "Nite Owl", "Rorschach", "Doctor Manhattan",
                  "Silk Spectre", "Captain Thunder", "Granny Goodness", "Glorious Godfrey", "Steppenwolf", "Desaad",
                  "Johnny Quick", "Power Ring", "Ultraman", "Owlman", "Superwoman", "The Eradicator", "The Engineer",
                  "Jack Knight (Starman)", "Hourman", "Doctor Mid-Nite", "Sandman (Wesley Dodds)",
                  "Wesley Dodds (Sandman)", "Atom Smasher", "Wild Dog", "Orion", "Blue Devil", "Firehawk",
                  "Johnny Thunder", "Jesse Quick", "Mary Marvel", "Circe", "Trigon", "Neron", "Manchester Black",
                  "Mongal", "Simon Baz (Green Lantern)", "Jessica Cruz (Green Lantern)", "The Outsider",
                  "Talon (Court of Owls)", "Lightning Lad", "Saturn Girl", "Cosmic Boy", "Mon-El", "Dream Girl",
                  "Brainiac 5", "The Legion of Super-Heroes", "XS (Nora West-Allen)", "Jay Garrick (The Flash)",
                  "Max Mercury", "Impulse (Bart Allen)", "Johnny Quick (Crime Syndicate)",
                  "Huntress (Helena Bertinelli)", "Karate Kid", "Dawnstar", "Bouncing Boy", "Timber Wolf", "Mxyzptlk",
                  "Lightning Lord", "Shayera Hol (Hawkgirl)", "Bronze Tiger", "Aqualad"]